### ISSUE TITLE
Cannot find module 'jsonwebtoken'

### ISSUE THREAD

**Issue by TAC911** [blockapps/blockapps-ba#100]
Using Macos and having a STRATO node running (`http://localhost` resolves fine using version `SMD v0.7.0 - Enterprise`) and installing from scratch (`npm i`) I'm getting the error:

```
Error: Cannot find module 'jsonwebtoken'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tac/Dev/Blockchain/Blockapps/blockapps-ba/node_modules/blockapps-rest/lib/oauth.js:1:75)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tac/Dev/Blockchain/Blockapps/blockapps-ba/node_modules/blockapps-rest/lib/common.js:29:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

I deleted the `node_modules` folder and re-executed `npm i` but with no help.

Any support you can provide on this?

**Comment by th0114nd** [comment]
Hello, I've filed a PR that I believe should resolve this: https://github.com/blockapps/blockapps-ba/pull/101.

You could see if the `relock` branch works for you. I've also found that with a stale lock file `npm install; npm install; npm run deploy` will work, although I couldn't explain why updating the package-lock.json file takes two passes. The other alternative is to issue `npm config set package-lock false` to ignore package-lock.json's entirely.

**Comment by TAC911** [comment]
Thanks @th0114nd. I tried the `npm config set package-lock false` command and it worked.

**Comment by th0114nd** [comment]
Glad to hear it
