### ISSUE TITLE
Bug in npm run start

### ISSUE THREAD

**Issue by ijazm** [blockapps/blockapps-ba#46]
/home/ubuntu/blockapps-ba/server/api/v1/projects/projects.controller.js:54
    let listCallback, listParam;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup                                                                                        ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/blockapps-ba/server/api/v1/projects/inde                                                                                        x.js:3:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/blockapps-ba/server/routes.js:4:18)
    at Module._compile (module.js:410:26)

**Comment by samrit** [comment]
@ijazm Can you verify your `node --version`. This app requires node 7 or better.
