### ISSUE TITLE
Error in Accepting bid

### ISSUE THREAD

**Issue by ijazm** [blockapps/blockapps-ba#47]
Handle Event Error: Error: 2
    at /home/ubuntu/blockapps-ba/server/lib/project/projectManager.js:156:17
    at tryCatcher (/home/ubuntu/blockapps-ba/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/blockapps-ba/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/blockapps-ba/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/blockapps-ba/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/blockapps-ba/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ubuntu/blockapps-ba/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/blockapps-ba/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ubuntu/blockapps-ba/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

**Comment by samrit** [comment]
@ijazm Try cloning the latest master and running this with node 7.2 or better. That should work.
