### ISSUE TITLE
Getting module.js:487 error when deploying the application 

### ISSUE THREAD

**Issue by suchitgupta60** [blockapps/blockapps-ba#61]
@samrit 

**ubuntu@ip-222-21-2-222:~/Projects/blockapps-ba$** npm install g mocha
'+ mocha@3.5.0
'+ g@2.0.1
added 1 package and updated 1 package in 1.619s
**ubuntu@ip-222-21-2-222:~/Projects/blockapps-ba$** SERVER=ec2-22-234-222-222.compute-1.amazonaws.com npm run deploy

'> blockapps-ba@1.0.0 deploy /home/ubuntu/Projects/blockapps-ba
'> mocha server/dapp/dapp.deploy.js --config server/config/${SERVER:-localhost}.config.yaml -b && cp server/config/${SERVER:-localhost}.config.yaml ./config.yaml

module.js:487
    throw err;
    ^

Error: Cannot find module 'co-mocha'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/Projects/blockapps-ba/server/dapp/dapp.deploy.js:1:63)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /home/ubuntu/Projects/blockapps-ba/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/ubuntu/Projects/blockapps-ba/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/home/ubuntu/Projects/blockapps-ba/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/home/ubuntu/Projects/blockapps-ba/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockapps-ba@1.0.0 deploy: `mocha server/dapp/dapp.deploy.js --config server/config/${SERVER:-localhost}.config.yaml -b && cp server/config/${SERVER:-localhost}.config.yaml ./config.yaml`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockapps-ba@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-08-15T05_23_27_973Z-debug.log
**ubuntu@ip-222-21-2-222:~/Projects/blockapps-ba$** npm -v
5.3.0
**ubuntu@ip-222-21-2-222:~/Projects/blockapps-ba$** node -v
v8.3.0

**Comment by suchitgupta60** [comment]
And I am also getting this error when running deploy inside 'ui' folder.

**ubuntu@ip-222-21-2-222:~/Projects/blockapps-ba/ui$** SERVER=ec2-22-222-212-222.compute-1.amazonaws.com npm run deploy
npm ERR! missing script: deploy

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-08-15T05_40_31_819Z-debug.log

**Comment by samrit** [comment]
@suchitgupta60, you dont need to run deploy inside the ui. You only need to run it from the root folder. Run `npm i` to install all the dependencies before running the deploy script.

**Comment by suchitgupta60** [comment]
@samrit When I run it outside ui folder i.e from the root it gives me following error

module.js:487
throw err;
^
Also in the readme.MD file it says I need to run deploy from both root and inside ui folders.
![screen shot 2017-08-16 at 10 05 50 am](https://user-images.githubusercontent.com/12634462/29367381-b0dfb660-826a-11e7-89e8-bf7d73ebc6f3.png)

**Comment by samrit** [comment]
Try starting from scratch and following the instructions precisely as they are written. You need to install node dependencies. This is done by `npm i`. This needs to be done for both the server (root folder) and the web app (cd ui). Before you can run the application, you need to deploy the smart contracts it depends on. This is done **only once from the root folder** by using the command `npm run deploy`. You can then run the server and the ui separately using `npm run start` in the root and the ui folder.
