### ISSUE TITLE
Error deploying

### ISSUE THREAD

**Issue by thegrekle** [blockapps/blockapps-ba#70]
I am trying to deploy the sample app into the Azure Strato Marketplace image.

I have the VM running and have all the pre-req's installed.  When I execut npm run deploy I get the following error.  I've rebuilt several times, following the directions and have tried different node versions and currently am using specifically 7.2.

```
" -d "args={}" -d "contract=AdminInterface" -d "txParams={gasLimit:100000000,gasPrice:1}"  http://localhost/bloc/v2.1/users/Admin_130825_14999698/125ae3cede7c84d29baf91a496f4bed3707b2003/contract
    1) should upload the contracts


  0 passing (2s)
  1 failing

  1) Supply Chain Demo App - deploy contracts should upload the contracts:
     HttpError: 400 Bad Request: "src:299:43: Error: Undeclared identifier.\n  function setBidState(BidState newState) payable returns (ErrorCodes) {\n                                          ^---
--^\n": http://localhost/bloc/v2.1/users/Admin_130825_14999698/125ae3cede7c84d29baf91a496f4bed3707b2003/contract
      at node_modules/blockapps-rest/lib/rest_3.js:197:40
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

Thank you for any help you can offer.

**Comment by samrit** [comment]
@thegrekle Apologies for the late response. Could you please try again and let us know if it works?
