### ISSUE TITLE
Config.yaml not found

### ISSUE THREAD

**Issue by ravindraprasad75** [blockapps/blockapps-ba#87]
I am getting below error. Can you please help?
> blockapps-ba@2.1.0 start /Users/ravindraprasad/Ravindra/100days/Blockchain/blockapps-ba
> node server/index.js

command line: [ '/usr/local/Cellar/node/9.8.0/bin/node',
  '/Users/ravindraprasad/Ravindra/100days/Blockchain/blockapps-ba/server/index.js' ]
config filename: config.yaml
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open 'config.yaml'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at getYamlFile (/Users/ravindraprasad/Ravindra/100days/Blockchain/blockapps-ba/node_modules/blockapps-rest/lib/config.js:11:29)
    at Object.<anonymous> (/Users/ravindraprasad/Ravindra/100days/Blockchain/blockapps-ba/node_modules/blockapps-rest/lib/config.js:28:20)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ravindraprasad/Ravindra/100days/Blockchain/blockapps-ba/node_modules/blockapps-rest/lib/common.js:10:16)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)

**Comment by pm-Egor-Genning** [comment]
https://github.com/blockapps/blockapps-ba/pull/94
